webtalk_init -webtalk_dir C:/Users/Musab/OneDrive - Habib University/4th Semester/CA/Labs/Lab 11/CA_Project_CPU/SingleCycleCPU/SingleCycleCPU.sim/sim_1/behav/xsim/xsim.dir/risc_v_pipelined_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Apr 17 08:37:47 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "545a3981-2b74-4c28-8553-092e97eae41f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d21c0380bdf44c3581dcb8bfbf3716ba" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "77" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 4800H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2895 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2940265 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.50_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15704_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2515062009 -regid "" -xml C:/Users/Musab/OneDrive - Habib University/4th Semester/CA/Labs/Lab 11/CA_Project_CPU/SingleCycleCPU/SingleCycleCPU.sim/sim_1/behav/xsim/xsim.dir/risc_v_pipelined_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Musab/OneDrive - Habib University/4th Semester/CA/Labs/Lab 11/CA_Project_CPU/SingleCycleCPU/SingleCycleCPU.sim/sim_1/behav/xsim/xsim.dir/risc_v_pipelined_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Musab/OneDrive - Habib University/4th Semester/CA/Labs/Lab 11/CA_Project_CPU/SingleCycleCPU/SingleCycleCPU.sim/sim_1/behav/xsim/xsim.dir/risc_v_pipelined_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
